### PR TITLE
wifi-unstuck-wa: add new package with radio workarrounds

### LINKED ISSUE #620: Review network profiles and workarrounds specially from quintanalibre
All the uci-defaults list is:
```
/rom/etc/uci-defaults/00_uhttpd_ubus
/rom/etc/uci-defaults/03_network-switchX-migration
/rom/etc/uci-defaults/03_network-vlan-migration
/rom/etc/uci-defaults/04_led_migration
/rom/etc/uci-defaults/09_fix-checksum
/rom/etc/uci-defaults/09_fix-seama-header
/rom/etc/uci-defaults/10-fstab
/rom/etc/uci-defaults/10_migrate-shadow
/rom/etc/uci-defaults/12_network-generate-ula
/rom/etc/uci-defaults/13_fix_group_user
/rom/etc/uci-defaults/20_migrate-feeds
/rom/etc/uci-defaults/30_uboot-envtools
/rom/etc/uci-defaults/50-set-automount
/rom/etc/uci-defaults/80_libremap-agent
/rom/etc/uci-defaults/88_lime-merge-factory-defaults
/rom/etc/uci-defaults/89_lime-release
/rom/etc/uci-defaults/90-pirania-cron
/rom/etc/uci-defaults/90_dnsmasq-lease-share
/rom/etc/uci-defaults/90_lime-app
/rom/etc/uci-defaults/90_lime-banner
/rom/etc/uci-defaults/90_lime-customize-profile
/rom/etc/uci-defaults/90_watchping
/rom/etc/uci-defaults/91-disable_passwd_login
/rom/etc/uci-defaults/91-set_libremap
/rom/etc/uci-defaults/91-set_system_opts
/rom/etc/uci-defaults/91_lime-config
/rom/etc/uci-defaults/92-cron-workaround-tasks
/rom/etc/uci-defaults/92_add-lime-repos
/rom/etc/uci-defaults/94-dnsmasq_startup_workaround
/rom/etc/uci-defaults/95-lime-app-rpc-acl
/rom/etc/uci-defaults/96-minido-info
/rom/etc/uci-defaults/96-thisnode-info-translation
/rom/etc/uci-defaults/97-dropbear
/rom/etc/uci-defaults/98-disable-fbw-and-pirania
/rom/etc/uci-defaults/99-restart-babeld-workaround
/rom/etc/uci-defaults/99-save-last-known-path-to-internet
```

### PR DESCRIPTION
**Pull request by spiccinini**
A collection of workarrounds to radio and/or radio driver bugs.  At this moment it is very simple and only performs periodic scans at two frequencies of radios that have mesh or adhoc interfaces.

Partially fixes #620

### CODE REVIEW

**Comment by spiccinini** [comment]
> If I got it right, this does a scan every 10 minutes, right?

Yes

> Wouldn't it be better to use [cotonete](https://github.com/nicopace/cotonete) for detection of the problem and make it run this script as a fix?

Yes! But lets have something that works until we have cotonete back working (and then we can remove the cronjob).

**Comment by ilario** [comment]
> lets have something that works until we have cotonete back working (and then we can remove the cronjob)

Ok.
Anyway, @nicopace what was missing from Cotonete? Just the fix, right?

**Comment by ilario** [comment]
I have a router I use as a client, and from times to times it seems to get deaf also.
Do you think it would make sense to add `sta` additionally to `adhoc` and `mesh` to the kind of interfaces which can get stuck?
As soon as that interface will get deaf I'll be able to test if it gets detected by Cotonete and fixed by this :D

**Comment by spiccinini** [comment]
> I have a router I use as a client, and from times to times it seems to get deaf also.
> Do you think it would make sense to add `sta` additionally to `adhoc` and `mesh` to the kind of interfaces which can get stuck?
> As soon as that interface will get deaf I'll be able to test if it gets detected by Cotonete and fixed by this :D

Yes, I didn't know about deaf in ap/sta. Which driver is it?

**Comment by ilario** [comment]
> Yes, I didn't know about deaf in ap/sta. Which driver is it?

Well, I still have to confirm that the problem is the deaf interface (looks so: it is associated but it does not ping, but I want to check using Cotonete).
The device is a Ubiquiti Nanostation LoCo M2, with ath9k driver.

**Comment by spiccinini** [comment]
> Could need to be expanded to station interfaces and integrated with Cotonete, but as a temporary fix seems very good and very fast (the wireless interface stays down for less than half of a second)!

Yes it takes 0.17s per interface so it is almost transparent. I will add station support

**Comment by gmarcos87** [comment]
Aproved. In the paravachasca network we are suffering from a new set of bugs incorporated in these latest releases of openwrt. For some of them we don't have workaround or ways to replicate them. Among the list of detected bugs are:
- Deaf radios that don't respond to the scan workarround
- Completely wrong MCS negotiations
- Some 5ghz channels that do not work

**Comment by spiccinini** [comment]
> Aproved. In the paravachasca network we are suffering from a new set of bugs incorporated in these latest releases of openwrt. For some of them we don't have workaround or ways to replicate them. Among the list of detected bugs are:
> 
>     * Deaf radios that don't respond to the scan workarround
> 
>     * Completely wrong MCS negotiations
> 
>     * Some 5ghz channels that do not work

Thanks! for the deaf radios I hope I can access a device in that state to debug and write a proper fix.

**Pull request merged**
