### PR TITLE
add tail command to remove first character of the string

### LINKED ISSUE #888: OPKG does not find our Packages.gz for releases
Just tested an image downloaded from 
http://repo.libremesh.org/expansive_emancipation/2020.1/targets/ath79/generic/

```
# opkg update
[...]
Downloading http://feed.libremesh.org/2020.1/Packages.gz
*** Failed to download the package list from http://feed.libremesh.org/2020.1/Packages.gz

Downloading http://feed.libremesh.org/profiles/Packages.gz
Updated list of available packages in /var/opkg-lists/profiles
Downloading http://feed.libremesh.org/profiles/Packages.sig
Signature check passed.
Collected errors:
 * opkg_download: Failed to download http://feed.libremesh.org/2020.1/Packages.gz, wget returned 8.
```

OPKG looks for `.../2020.1/...` but, as the directory in the feed is `v2020.1`: https://github.com/libremesh/lime-feed/tree/gh-pages/v2020.1, it should look for `.../v2020.1/...` instead.

I suppose that the fix is as easy as add a `v` here (?):

https://github.com/libremesh/lime-packages/blob/06399e5de7fb7b9d3cf13c19f7bf70accb11299a/packages/lime-system/files/etc/uci-defaults/92_add-lime-repos#L18

### PR DESCRIPTION
**Pull request by RhnSharma**
Fixes #888
Hi @ilario, I have made the changes as discussed in https://github.com/libremesh/lime-packages/issues/888#issuecomment-889988221. 
Let me know if this needs any changes.
Thanks

### CODE REVIEW

**Comment by ilario** [comment]
I fear I proposed the solution in a rush and it's wrong.
That "$TAG" is going to be used also for "master", right? @spiccinini @aparcar 
In that case we have to remove the first character ooonly if it's a tag like `v2020.1`.
So the `| tail -c +2` could be replaced by `| perl -pe 's/v([0-9])/$1/'` (hoping that that environment has perl).
Sorry @RhnSharma for the mess, could you change the content of this pull request or open another?
Thanks for your patience

**Comment by RhnSharma** [comment]
@ilario I have made the change you suggested. Please take a look at it and let me know if this needs any changes.
Thanks

**Review by ilario — APPROVED** [review]
Looks good to me (hoping that perl is available there). We should merge this and then rename the directories in lime-feed.

**Comment by spiccinini** [comment]
Looks good to me! thanks for doing it

**Review by spiccinini — APPROVED** [review]

**Pull request merged**
