### PR TITLE
Remove sleepy radio hook

### PR DESCRIPTION
**Pull request by p4u**
The implementation of this "dirty fix" should not affect all targets,
but only those which are afected.

The implementation is just wrong, smonit executes quick-fix threee times
and then 1 time long fix if the problem persists.

Signed-off-by: p4u <p4u@dabax.net>

### CODE REVIEW

**Comment by p4u** [comment]
This quick fix was added in some release to avoid a problem on wdr3500/3600/4300 routers. But it was a patch just for that release, I should have never been merged to master.

In addition the implementation is wrong, so it does not even works (only the first 20 minutes)...

So I'd remove it until a better one is implemented (if still needed). If some community wants to keep using it, they can use the network-profiles.

**Comment by gmarcos87** [comment]
Hi @p4u, Can you give more information that this bug is resolved in 18.06.1?

**Comment by p4u** [comment]
I don't know (actually I never undestood this bug).

But I know that this patch does not fix it, so there is no point of having this dirty script here.

**Comment by p4u** [comment]
I'm not saying it does not exist, I'm just saying I have never experienced it and the removed file on this PR does not fix. 

If "cotonete" workaround works, perfect! But this PR is still valid.

**Comment by gmarcos87** [comment]
The difference is that cotonete is an optional package and smonit is included in all libremesh by default

**Comment by p4u** [comment]
Then, rather cotonete should be enabled by default or smonit script must be fixed. But the current one just does not work.

In addition this workaround should be executed **only** when the device is affected by the bug, it must not be enabled always by default.

**Comment by aparcar** [comment]
Why don't add cotonete per default? Does it add any overhead on *not affected* devices?

**Comment by ilario** [comment]
Related #144

**Comment by nicopace** [comment]
This package is an improvement of the implementation done in smonit, that shouldn't be removed.
The issue with the smonit implementation is that it takes time since the moment it detects the issue till the moment it implements a solution, though leaving the node unconnected during that time.
The specific implementation within smonit is part of trunk, so i don't see why that would be a reason to take it out of the repository.
In fact, this is a rework of the smonit implementation that the original author of the solution the smonit implementation was based on (@nicoechaniz ) and I invested a lot of time in polishing it.
The minimal task I woud say, instead of removing it, would be to see why in some cases is not working and fixing it, cause this provides a much faster (so more effective) way of dealing with the issue smonit (and the workarounds in quintanalibre profile for example) deal with.

**Comment by nicopace** [comment]
For now it doesn't implement the fix, only logs when the problem is reproducible, so no harm done on interfaces that don't have the issue.

Please, don't remove.

**Comment by nicopace** [comment]
Sorry @p4u, I rushed into it.
Will review now...

**Comment by p4u** [comment]
Regarding smonit, her the context: https://github.com/libremesh/lime-packages/commit/e8a27e19d6cb470e035d5437df9adabf8240e926


```
Small and modular monitor for daemons.
It executes every 5 minutes and run a set of hooks to check the
daemons and status of the system. Hooks are installed on /etc/smonit and
must define a function for quickfix (like daemon restart) and longfix
(like rebuild configuration for daemon). Longfix is launched only if
after 3 quickfixes the problem is not solved. Logs are stored on /tmp/smonit/<daemon_name>.
```

**Comment by p4u** [comment]
And here an example of what happens with sleepy_radio hook on a libremesh node. See last message `[2019/01/18 16:30] sleepy_radio -> No recovery after longfix, doing nothing else`

```
$ cat /tmp/smonit/smonit.log | grep sleepy
[2019/01/18 16:05] sleepy_radio -> Executing
[2019/01/18 16:05] sleepy_radio -> Status: error
[2019/01/18 16:05] sleepy_radio -> Fails:0, executing quick fix
[2019/01/18 16:10] sleepy_radio -> Executing
[2019/01/18 16:10] sleepy_radio -> Status: error
[2019/01/18 16:10] sleepy_radio -> Fails:1, executing quick fix
[2019/01/18 16:15] sleepy_radio -> Executing
[2019/01/18 16:15] sleepy_radio -> Status: error
[2019/01/18 16:15] sleepy_radio -> Fails:2, executing quick fix
[2019/01/18 16:20] sleepy_radio -> Executing
[2019/01/18 16:20] sleepy_radio -> Status: error
[2019/01/18 16:20] sleepy_radio -> Fails:3, executing long fix
[2019/01/18 16:25] sleepy_radio -> Executing
[2019/01/18 16:25] sleepy_radio -> Status: error
[2019/01/18 16:25] sleepy_radio -> No recovery after longfix, doing nothing else
[2019/01/18 16:30] sleepy_radio -> Executing
[2019/01/18 16:30] sleepy_radio -> Status: error
[2019/01/18 16:30] sleepy_radio -> No recovery after longfix, doing nothing else

```

**Comment by gmarcos87** [comment]
As longfix we could call wifi on all ad-hoc or mesh interfaces. This is the fix that takes the longest but guarantees the result.

**Comment by p4u** [comment]
> As longfix we could call wifi on all ad-hoc or mesh interfaces. This is the fix that takes the longest but guarantees the result.

Yes, that would make more sense. Quick fix makes the scan and longfix recreates the wifi devices... but **that requires a very trusty way of detecting the problem**, cause that's very drastic (actually the scann is also quite dramatic in therms that the radio stops working during a period). Please, take into account that many people around the world does not use tplink-wdr neither ath9k driver.

**Pull request merged**
