### PR TITLE
lime-smart-wifi: add package, fix #306

### LINKED ISSUE #306: separate Mesh and AP radio based on frequencies
Using an encrypted 11s mesh and encrypted AP on the same radio (2.4GHz or 5GHz) does not work as reported [here](https://github.com/libremesh/lime-packages/issues/208).

To archive this feature it's [possible](https://github.com/ilario/lime-packages/blob/dee5ba5da8d54b0fec744070269b4db33cba7de4/packages/lime-docs/files/lime-example#L76) to set individual configurations, but due to the usage of [foreach](https://github.com/libremesh/lime-packages/blob/6e152fc2f08838f722ac5240a1c2ec81c11b1994/packages/lime-system/files/usr/lib/lua/lime/config.lua#L48) in the [wireless.lua](https://github.com/libremesh/lime-packages/blob/6e543c79a08e41482f1fdd0214dbf93e97f5d312/packages/lime-system/files/usr/lib/lua/lime/wireless.lua#L78) module it's not possible to set that in `lime-defaults'.

### PR DESCRIPTION
**Pull request by aparcar**
fix separate Mesh and AP radio based on frequencies #306

1 radio with dual band is not supported due to missing device for
  testing, this will be added.

automatically swaps channels if multible radios on same freq exist

tested on tp link wdr 4300

also introduce new function to utils to check if an element is inside an
array

reopend due to git messup

Signed-off-by: Paul Spooren <spooren@informatik.uni-leipzig.de>

### CODE REVIEW

**Comment by aparcar** [comment]
Depends on https://github.com/libremesh/lime-packages/pull/320

**Comment by aparcar** [comment]
Just tested the app with a xiami miwifi router and it works as intended. 
In the default we could enable 2.4Ghz mesh per default so the devices stay compatible to single 2.4Ghz band devices.

@p4u @G10h4ck please merge this patch and the #320

**Comment by p4u** [comment]
I'd suggest a change on the configuration section. Instead of adding the smart-wifi options to the lime.wifi section (which is used by lime-system) I think it's much better to separate it in another section. For instance

```
config lime smart-wifi
 list channels_2ghz 11
 list channels 2ghz 6
 list channels 5ghz 36
 list channels 5ghz 48
 option mesh_5ghz 1
 option ap_5ghz 0
 option mesh_2ghz 0
 option ap_2ghz 1
 option all_to_mesh 0
 option all_to_ap 0
```

However this options cannot be added in compile time to /etc/config/lime-defaults because this file is owned by lime-system package. Then a uci-defaults script is required to check if the option exist and set it if not. Example for an entry

> uci -q get lime-defaults.smart-wifi.mesh_2ghz || uci set lime-defaults.smart-wifi.mesh_2ghz=0

It is better to have all default values in config files instead of hardcoding it into the code (I'm not saying not to hardcode but they must also be visible in the config file).

**Comment by aparcar** [comment]
@p4u i really dislike the idea of using UCI scripts. All settings should be configurable in the defaults package. I don't want the user to understand the uci-defaults system plus the UCI command syntax, don't you think?

**Comment by p4u** [comment]
> @p4u i really dislike the idea of using UCI scripts. All settings should be configurable in the defaults package. I don't want the user to understand the uci-defaults system plus the UCI command syntax, don't you think?

I don't think you understand what I'm proposing. User must NOT deal with uci-defaults, but if an option is not set (right now your commit does not include any option) a uci-default script would create it on first boot. 

The user still can have its own /etc/config/lime-defaults file with the options, as usual.

**Comment by p4u** [comment]
The other approach to not make this options invisible is to add them in lime-defaults but as I said before, this config file is owned by another package (lime-system). Adding options of one package to another is not a good aproach IMO.

**Comment by p4u** [comment]
> The other approach to not make this options invisible is to add them in lime-defaults but as I said before, this config file is owned by another package (lime-system). Adding options of one package to another is not a good aproach IMO.

Or let's just do it... my concern is to make the lime-defaults file too big if we start adding all options from all libremesh related packages

**Comment by aparcar** [comment]
Good I'll add defaults via UCI in it's own section. That simplifies the removal as well

**Comment by aparcar** [comment]
> the default we could enable 2.4Ghz mesh per default so the devices stay compatible to single 2.4Ghz band devices

@p4u

**Comment by p4u** [comment]
ok

**Comment by aparcar** [comment]
@p4u all done hopefully

**Comment by aparcar** [comment]
@p4u ping

**Comment by ilario** [comment]
Congrats for the amazing package :D 
Can we have a commented configuration example in packages/lime-docs/files/lime-example?

**Comment by aparcar** [comment]
sure, will create that later

**Pull request merged**
