### PR TITLE
Add check-internet package

### PR DESCRIPTION
**Pull request by spiccinini**
Very simple package with a `check-internet` command that uses HTTP to check for internet.

Also use this in `last_internet`.

### CODE REVIEW

**Comment by ilario** [comment]
And we should really push this package to the OpenWrt's repositories!

**Comment by ilario** [comment]
Seems that OpenWrt is migrating away from wget towards uclient-fetch, see discussion on #720.
Anyway I just realized that the wget dependency was missing.

**Comment by spiccinini** [comment]
> Seems that OpenWrt is migrating away from wget towards uclient-fetch, see discussion on #720.
> Anyway I just realized that the wget dependency was missing.

if I remember correctly wget is part of busybox and it is built by default.

Anyway It is good idea to move to the main openwrt supported http client!

**Comment by spiccinini** [comment]
I've opened https://github.com/libremesh/lime-packages/pull/721

**Comment by spiccinini** [comment]
So I was wrong, `wget` is a symlink to uclient-fetch, so yes the dependency was missing (we may use #721 to correct this)

**Pull request merged**
