### PR TITLE
Update README.md

### PR DESCRIPTION
**Pull request by vcuculo**
:point_up: :point_up: :point_up:
#247

### CODE REVIEW

**Comment by ilario** [comment]
Can you also remove the link at the end of the page pls :)
This fixes #247

**Comment by vcuculo** [comment]
Here you served, dear @ilario  :kissing_smiling_eyes:

**Comment by ilario** [comment]
@G10h4ck @altergui there was a conflict here because of modifying two adjacent lines with the PR #250 
Is it ok to merge or should we clean the history before? How?

**Comment by G10h4ck** [comment]
At first glance I don't see the cnflict, BTW if any exists it should be fixed here in the PR using pulling from or rebasing on top official repo before merge attempt

Cheers

**Comment by ilario** [comment]
@G10h4ck you don't see the conflict because I tried to solve it with the online methods from Github, can you check the commits list on this PR, does it look ok?

**Pull request merged**
