### PR TITLE
shared-state-async bump for late bleach fixup

### PR DESCRIPTION
**Pull request by G10h4ck**

### CODE REVIEW

**Comment by ilario** [comment]
Thanks!
Should this be included in the release candidate branch?
https://github.com/libremesh/lime-packages/tree/2024.1

**Comment by G10h4ck** [comment]
related to https://github.com/libremesh/lime-packages/issues/1105

**Review by javierbrk — APPROVED** [review]
tested and working

**Review by selankon — APPROVED** [review]

**Comment by javierbrk** [comment]
> Thanks! Should this be included in the release candidate branch? https://github.com/libremesh/lime-packages/tree/2024.1

yes !

**Comment by ilario** [comment]
Done!
https://github.com/libremesh/lime-packages/commit/5cd8833b84499e484512153eeed407e442cc6de5

Please tell me if any other recent commit has to be included, or include it yourselves :)

**Pull request merged**
