### PR TITLE
SSH banner: Added pointer to offline documentation in /docs

### LINKED ISSUE #616: Point out in SSH banner that the documentation is in /docs
See discussion on #195

### PR DESCRIPTION
**Pull request by ilario**
Fix #616

### CODE REVIEW

**Review by spiccinini — APPROVED** [review]
great!

**Comment by ilario** [comment]
Hey, I just thought: the line I added is only true when lime-docs* is installed, which is very likely but not 100% sure. Do you think it's worth to use an uci-defaults script in lime-docs-minimal to append this line to the banner? Or this way is good enough?

**Comment by aparcar** [comment]
Yea I'd say make it optional that it only shows up if /docs exists.

**Comment by ilario** [comment]
> Yea I'd say make it optional that it only shows up if /docs exists.

Mh, why is this better than using another uci-defaults script in lime-docs-minimal package?

**Comment by aparcar** [comment]
I guess deleting the docs later on would cause to keep the message, but as that's unlikely I'm fine with both.

**Comment by ilario** [comment]
I moved the thing to the lime-docs-minimal package.
And I took advantage to advertise that the docs are accessible also via web interface and to rename lime-example to lime-example.txt so that the browsers open it as a text file (instead than proposing the download as a binary file).

**Review by aparcar — APPROVED** [review]

**Pull request merged**
