### PR TITLE
Update Babeld option "wired" -> "type"

### PR DESCRIPTION
**Pull request by ilario**
See original report on https://lists.libremesh.org/pipermail/lime-users/2020-October/001741.html
I tested coarsely, also because I have no idea on how to check if the option is actually doing anything.

### CODE REVIEW

**Review by aparcar — APPROVED** [review]

**Comment by ilario** [comment]
I checked if this should work also on the Babeld version from OpenWrt 18.06 and yes, it should.

In [OpenWrt 19.07, Babeld 1.9.2 is used](https://github.com/openwrt-routing/packages/blob/openwrt-19.07/babeld/Makefile) and in there, the [usage of the wired option is deprecated](https://github.com/jech/babeld/blob/babeld-1.9.2/configuration.c#L561).

In [OpenWrt 18.06, Babeld 1.8.5 is used](https://github.com/openwrt-routing/packages/blob/openwrt-18.06/babeld/Makefile) and in there, the [usage of the wired option is deprecated](https://github.com/jech/babeld/blob/babeld-1.8.5/configuration.c#L550).

**Review by spiccinini — APPROVED** [review]

**Comment by G10h4ck** [comment]
@ilario @aparcar @spiccinini did you check/test if the openwrt babeld init script support the `type` option too?

AFAIR when I wrote the lime module babeld C code already deprecated the `wired` option but the Openwrt babeld init script didn't seem support the `type` option yet.

In current openwrt-routing repository init script https://github.com/openwrt-routing/packages/blob/master/babeld/files/babeld.init#L129 it seems that the option would be just passed down "as is" but that is just what it seems to  me at first glance.

Be very careful with this kind of changes, they seems very little but they may unexpectedly break entire networks in a non trivial to debug way at next update.

**Comment by spiccinini** [comment]
I have tested ir only with the LibreRouterOs babeld init script that is not the upstreap script. Maybe que can revert this until que are very sure that it is working?

**Comment by spiccinini** [comment]
@ilario can you test using  `wirelesstypo` instead of `wireless` and see if it does not start (so we can conclude that the babeld script is working) ?

**Comment by ilario** [comment]
> @ilario can you test using `wirelesstypo` instead of `wireless` and see if it does not start (so we can conclude that the babeld script is working) ?

Yes it works also for me.
With the typo I have:
`Couldn't parse configuration from file /var/etc/babeld.conf (error at line 4).`
without the typo I have:
```
Warning: couldn't determine channel of interface eth0-1_17.
Warning: couldn't determine channel of interface wlan0-mesh_17.
Warning: couldn't determine channel of interface wlan1-mesh_17.
Warning: couldn't determine channel of interface eth0_17.
Warning: couldn't determine channel of interface eth0-2_17.
```

**Comment by spiccinini** [comment]
Great thanks!

**Comment by spiccinini** [comment]
I've cherrypicked this into 20.09

**Pull request merged**
