### PR TITLE
fix #353

### LINKED ISSUE #353: wireless.lua: don't fail if no wifi modes are set
If no wifi modes are set the wireless configuration fails

### PR DESCRIPTION
**Pull request by aparcar**
Signed-off-by: Paul Spooren <spooren@informatik.uni-leipzig.de>

### CODE REVIEW

**Comment by G10h4ck** [comment]
someone know why CI fails?

**Comment by aparcar** [comment]
openwrt.org changed DNS. It's not populated everywhere yet.

The fix is valid anyway :relaxed:

**Comment by ilario** [comment]
After restarting the check, it succeeded, as @aparcar foresaw :)

**Comment by aparcar** [comment]
Feel free to merge

**Pull request merged**
