### PR TITLE
github-ci: replace deprecated set-env

### PR DESCRIPTION
**Pull request by spiccinini**
Hopefuly fIxes github action.
I am not exactly sure but as per the following documentation  https://docs.github.com/en/free-pro-team@latest/actions/reference/workflow-commands-for-github-actions#environment-files this should do the work.

### CODE REVIEW

**Comment by spiccinini** [comment]
It says that failed but it doesn't ... I don't understand
image

**Comment by ilario** [comment]
The error seems to be in peaceiris/actions-gh-pages old version we're using.
Can you edit the action file to point to a newer release?

https://github.com/peaceiris/actions-gh-pages/releases

**Comment by spiccinini** [comment]
Ok it should be working now

**Review by ilario — APPROVED** [review]

**Review by germanferrero — APPROVED** [review]

**Comment by ilario** [comment]
network-profiles actions are failing for the same reason: 
https://github.com/libremesh/network-profiles/actions

@spiccinini could you apply the same fix also there? Thanks!

**Pull request merged**
