### PR TITLE
Remove adhoc specific options from lime-defaults

### PR DESCRIPTION
**Pull request by ilario**
We moved from adhoc to IEEE 802.11s (mesh), so having options for adhoc in lime-defaults is just confusing.

### CODE REVIEW

**Comment by nicopace** [comment]
How this will work with the new changes @G10h4ck added to the lime apply?

**Comment by ilario** [comment]
Link to these changes pls?

**Comment by G10h4ck** [comment]
Those options should not be removed

**Comment by nicopace** [comment]
@G10h4ck can you share why? (so collective knowledge works?)
Cause @ilario thought taht it should be removed

**Comment by G10h4ck** [comment]
As you can see in the whole file we saves defaults for all modules even for those not instelled, nor used by default, that is because this way if one just enable a module it works like a charm without having to edit lot of configurations

**Comment by p4u** [comment]
Agree with @G10h4ck

**Comment by nicopace** [comment]
Thanks @G10h4ck !

**Comment by ilario** [comment]
Ok, thanks :)

**Pull request closed without merging**
