### PR TITLE
fft-eval: remove package

### PR DESCRIPTION
**Pull request by aparcar**
the package was accepted upstream and can therefore be deleted

### CODE REVIEW

**Comment by aparcar** [comment]
Please merge this PR if you can.

**Comment by gmarcos87** [comment]
good work!

**Comment by gmarcos87** [comment]
You can pull request from a brach of lime-packages. Because I have the sensation that this way the continuous integration does not run and that this commit right now would break again chef or lime-sdk.
Another option would be to send this pull-request to a new branch (not a master) and then see what happens.

**Comment by aparcar** [comment]
CI runs in PRS and commits

**Comment by gmarcos87** [comment]
@aparcar and where is the result of this pull request or commits?

**Comment by aparcar** [comment]
It just removes a package so the result is rather unspectacular. Thats why I did not create a feature branch...

**Comment by aparcar** [comment]
Just to illustrate https://github.com/libremesh/lime-packages/pull/479

**Comment by gmarcos87** [comment]
https://travis-ci.org/libremesh/lime-packages/builds/498318561#L644
> WARNING: No feed for package 'fft-eval' found

**Comment by aparcar** [comment]
http://snapshots.libremesh.org/branches/aparcar/

**Comment by G10h4ck** [comment]
I think we should fix the CI configuration as using personal forks for PR is the preferred way for contributions

**Comment by aparcar** [comment]
not possible as this could expose private variables used for ssh login

**Comment by aparcar** [comment]
https://github.com/libremesh/lime-packages/pull/479 moved

**Comment by aparcar** [comment]
> https://travis-ci.org/libremesh/lime-packages/builds/498318561#L644

>> WARNING: No feed for package 'fft-eval' found

Problem is the following list of dependencies: lime-full -> lime-app -> ubus-openairview -> fft-eval.

`lime-full` seems broken for weeks, I removed it from the chef instance as it only causes trouble.

**Pull request closed without merging**
