### PR TITLE
Fix batman-adv Originators Status WebUI.

### LINKED ISSUE #110: Fix batman-adv Status WebUI
Expected behaviour: see nodes

Actual behaviour: nodes are not being displayed

### PR DESCRIPTION
**Pull request by nicopace**
It solves part of the issue #110.
I have no environment to test the Gateways section, just the Originators one.

### CODE REVIEW

**Comment by p4u** [comment]
@altergui should review this pull request

**Comment by ilario** [comment]
Can't this info be taken from [alfred](https://git.open-mesh.org/alfred.git/blob_plain/refs/heads/master:/README) and its utility [batman-vis](https://downloads.open-mesh.org/batman/manpages/batadv-vis.html)?
Parsing the output of `batctl -o` sounds like a bad idea...

**Comment by nicopace** [comment]
I don't know... I just fixed what was broken... if there is a better way to do it, we could do it after we get fixed what was broken ;)

**Comment by p4u** [comment]
So @altergui is not responding and I don't see any point to not accept this fix.

Thanks.

**Comment by nicopace** [comment]
@p4u It solves part of the issue #110.
I have no environment to test the Gateways section, just the Originators one.

**Pull request merged**
