### PR TITLE
enable watchping to check for ipv6 connectivity

### PR DESCRIPTION
**Pull request by aparcar**
all work done by @dangowrt and based on https://github.com/libremesh/lime-packages/pull/71
This PR does not include the bmx6 script as the discussion is still
ongoing. As IPv6 watchping functionality is not directly related this
can be merged independently.

### CODE REVIEW

**Comment by G10h4ck** [comment]
I don't know in depth watchping, better if someone else with more related knoweldge merge this PR

**Comment by aparcar** [comment]
@dangowrt

**Comment by aparcar** [comment]
@G10h4ck the code was already approved in the original PR except for the (here left out) BMX6 part due to the ongoing ipv6 debate.

**Comment by p4u** [comment]
> I don't know in depth watchping, better if someone else with more related knoweldge merge this PR

I've reviewed the code, looks fine to me. I'd merge it today if there are no more reviews.

**Comment by aparcar** [comment]
@p4u If you don't mind I'd just merge it?

**Comment by p4u** [comment]
Done, thanks.

**Pull request merged**
