### PR TITLE
Fix lime-example disappeared from lime-system #125

### PR DESCRIPTION
**Pull request by G10h4ck**
This reverts commit 3e3c0f82feeabc82244cc210653d711222af66e9.

### CODE REVIEW

**Comment by ilario** [comment]
I propose to merge lime-example file with [lime-web/docs/config.txt](/libremesh/lime-web/blob/master/docs/config.txt) and to create a directory `/docs` containing:

* in case of default LiMe image, a copy of whole docs directory from lime-web repository, [this](https://github.com/libremesh/lime-web/tree/master/docs)
* in case of zero, mini LiMe images, just the config.txt file equivalent to lime-example

**Comment by p4u** [comment]
> I propose to merge lime-example file with lime-web/docs/config.txt and to create a directory /docs in the firmware filesystem root containing:

I like the idea of having a single (copy) file for the web page and for the firmware documentation.

**Comment by ilario** [comment]
So can we create two new packages in lime-packages called `lime-docs-minimal` and `lime-docs-complete` pulling respectively only `config.txt` and the whole `docs/` dir from lime-web?
Is it doable in a Makefile? If you point me to an example of how to do it I can do this.

**Comment by ilario** [comment]
I tried to write a lime-docs package for downloading the documentation .txt files from lime-web repo but with no luck. Would be easy if we make a tar package of the docs and host them on the website. If you want to see my tentative (and maybe fix it) [here you are](https://github.com/ilario/lime-packages/blob/develop-lime-docs/packages/lime-docs/Makefile).

**Comment by p4u** [comment]
You can use this link: https://raw.githubusercontent.com/libremesh/lime-web/master/docs/config.txt

As an example for defining two packages in a single Makefile, you can use this one: https://github.com/libremesh/lime-packages/blob/develop/packages/lime-basic/Makefile

**Comment by ilario** [comment]
Thanks, I think I got it mostly working, there's just a **dependency problem** 'cause I made lime-docs (which copies all the content of docs dir) depending on lime-docs-minimal (which copies just config.txt), maybe a bad idea. Can you review the [Makefile](https://github.com/ilario/lime-packages/blob/develop-lime-docs/packages/lime-docs/Makefile)?

**Comment by ilario** [comment]
I'm also trying writing separated packages, see [this](https://github.com/ilario/lime-packages/blob/develop-lime-docs-separated/packages/lime-docs/Makefile) and [this](https://github.com/ilario/lime-packages/blob/develop-lime-docs-separated/packages/lime-docs-minimal/Makefile) Makefiles.

**Comment by ilario** [comment]
Now it compiles and image contains the files, I'm going to make the PR.

**Comment by ilario** [comment]
PR #140 replaces this one for complying with @p4u comments

**Comment by mdmubarak** [comment]
I am Mubarak Dada, a computer programmer with more than 7 years experience
coding. I was fortunate to know about Libre router at the just concluded
Africa Internet Summit and i will love to be join the development team. I
code in C, C++, Python, Firtran and C#, i recently started learning lua. I
have done several projects and worked on big data and artificial
intelligence. I have worked with Apache Spark, Hadoop and TensorFlow. I
hope in making the libre router and it&#39;s associated components more
intelligent and geek free if i am given the chance to work with the team.
Thank you

Kind Regards

Mubarak

**Comment by nicopace** [comment]
@mdmubarak Great to hear that you want to approach this development community.
Let me suggest you to send your welcome message via http://lists.libremesh.org/mailman/listinfo/lime-dev so everyone can welcome you accordingly :)

**Comment by mdmubarak** [comment]
Hello there,

I just signed the petition "The British Council: STOP ENGLISH PROFICIENCY
EXAMS FOR AFRICANS FROM COMMONWEALTH COUNTRIES" and wanted to see if you
could help by adding your name.

Our goal is to reach 4,925 signatures and we need more support. You can
read more and sign the petition here:

https://chn.ge/2OsMKpz

Thanks!
Mubarak

**Pull request closed without merging**
