### PR TITLE
Add how to contribute guide

### PR DESCRIPTION
**Pull request by gmarcos87**
@ilario, do you think that more information is needed on how to test the packages or the system of continuous integration?

### CODE REVIEW

**Comment by ilario** [comment]
I think it's great, just a thing: in lime-packages there's no master branch, the default one is develop, and the releases are the numbered ones. Can you adapt the "Branch Names" section?

**Comment by gmarcos87** [comment]
Can you clarify the difference between hotfix, sandox and feature in the naming convention? So I include that in relation to branch names.

**Comment by ilario** [comment]
@G10h4ck @p4u @altergui @nicoechaniz pls

**Comment by gmarcos87** [comment]
### `<type>/<name>`

#### `<type>`
```
issue     - Code changes linked to a known issue.
feature   - New feature.
hotfix    - Quick fixes to the codebase.
sandbox   - Experiments (will never be merged).
```

#### `<name>`
Always use dashes to seperate words, and keep it short.

#### Examples
```
feature/smonit
hotfix/driver-xxx
sandbox/new-crazy-thing
```

**Comment by ilario** [comment]
sounds good :)

**Pull request merged**
