### PR TITLE
ubus-lime-utils place scripts in /etc/udhcpc.user.d/

### LINKED ISSUE #927: ubus-lime-utils file conflict when compiling with OpenWrt 22.03
There's a file conflict when compiling on top of OpenWrt 22.03.0-rc4 between:
https://github.com/libremesh/lime-packages/blob/400ac95448a1f1d5a83496488e40c302cde766f0/packages/ubus-lime-utils/files/etc/udhcpc.user
and:
https://github.com/openwrt/openwrt/blob/130118f7aa3191a2afd244d49e3057d4c5688676/package/network/config/netifd/files/etc/udhcpc.user

This is what the error looks like:

```
Collected errors:
 * check_data_file_clashes: Package ubus-lime-utils wants to install file /home/ilario/software/openwrt/build_dir/target-mips_24kc_musl/root-ath79/etc/udhcpc.user
	But that file is already provided by package  * netifd
 * opkg_install_cmd: Cannot install package lime-app.
 * check_data_file_clashes: Package ubus-lime-utils wants to install file /home/ilario/software/openwrt/build_dir/target-mips_24kc_musl/root-ath79/etc/udhcpc.user
	But that file is already provided by package  * netifd
 * opkg_install_cmd: Cannot install package ubus-lime-utils.
make[2]: *** [package/Makefile:70: package/install] Error 255
```

### PR DESCRIPTION
**Pull request by ilario**
Fix #927 
Still to be tested. Specifically, it is not obvious that it works on OpenWrt 19.07, while it should work on 22.03 as that directory is already present there.

### CODE REVIEW

**Comment by ilario** [comment]
On OpenWrt 19.07 the content of `/etc/udhcpc.user.d/` does not get executed and the `/etc/udhcpc.user` file does not exist ( https://github.com/openwrt/openwrt/tree/openwrt-19.07/package/network/config/netifd/files/etc ), but gets executed if it exists ( 
https://github.com/openwrt/openwrt/blob/openwrt-19.07/package/network/config/netifd/files/lib/netifd/dhcp.script#L108 ).

On OpenWrt 22.03 the content of `/etc/udhcpc.user.d/` does get executed ( https://github.com/openwrt/openwrt/blob/openwrt-22.03/package/network/config/netifd/files/lib/netifd/dhcp.script#L116-L118 ) and the `/etc/udhcpc.user` file does exist ( https://github.com/openwrt/openwrt/blob/openwrt-22.03/package/network/config/netifd/files/etc/udhcpc.user ).

For having something that works on both we could:
add the `/etc/udhcpc.user.d/50-client-wwan-watchping` file as in this PR
and
create a uci-defaults script that checks if the `/etc/udhcpc.user` is already existing and otherwise creates it with some lines executing the `/etc/udhcpc.user.d/` content.

Anyone has a better solution?

**Comment by ilario** [comment]
Situation on OpenWrt 19.07:

* executing manually udhcpc, the script gets executed (causing another issue: #956)
* running it from lime-app I didn't try

Situation with OpenWrt 22.03

* executing manually udhcpc, the script does not get executed
* running it from lime-app (after disabling ieee80211s for circumventing #957), the script gets executed

So in my opinion this can be merged.

**Comment by ilario** [comment]
Ping @spiccinini @G10h4ck @selankon I think this is ready to merge, can you review it?

**Comment by G10h4ck** [comment]
let's leave this for after retargetting to OpenWrt development version

**Comment by ilario** [comment]
> let's leave this for after retargetting to OpenWrt development version

Ok, makes sense.

**Comment by ilario** [comment]
Can we merge this now?

**Comment by aparcar** [comment]
Please go ahead

**Comment by G10h4ck** [comment]
Please just drop the OpenWrt 19 compatibility script

**Comment by ilario** [comment]
Thanks for removing the unneeded script!

**Pull request merged**
