### PR TITLE
Feature/fbw verbose scanning

### PR DESCRIPTION
**Pull request by selankon**
Implements necessary logic to show scan results on the frontend:

* Save mesh scan results on a file located at `/tmp/fbw/lime-scan-results.json`
* Send downloaded configuration files, together with scan results on `/ubus/search_networks/`
* If a network is selected before scan is finished, stop the scan service and restore the previous wifi configuration before applying the new configuration file
* Append the Ap bssid to the lime configuration file to show on the frontend what lime configuration file is associated to which scanned station. Now, the lime config files shows like: `lime-community__host__ql-refu-bbone__38:AB:C0:C1:D6:70` 
* Send trimmed configuration file sending only "wifi" section, needed for the frontend. 

Together with: https://github.com/selankon/lime-app/tree/feature/fbw-show-scan-results

### CODE REVIEW

**Comment by spiccinini** [comment]
Wow! This looks awesome!!

**Comment by selankon** [comment]
Add features on last commits:

* Verbose fetch configuration errors (example, if can't get `lime-community` file or the destination node is not configured yet)

**Comment by selankon** [comment]
Hopefully this is ready to merge among with  https://github.com/libremesh/lime-app/pull/339

**Comment by selankon** [comment]
This come with https://github.com/libremesh/lime-app/pull/334 which is already merged

**Pull request merged**
