### PR TITLE
remove libremap legacy

### PR DESCRIPTION
**Pull request by aparcar**
Signed-off-by: Paul Spooren <mail@aparcar.org>

### CODE REVIEW

**Comment by ilario** [comment]
Is it intentional to leave the `CONFIG_PACKAGE_lime-map-agent=m` entry in libremesh.sdk.config?

**Comment by aparcar** [comment]
good point, will remove thay

**Comment by aparcar** [comment]
Plesse recheck

**Comment by aparcar** [comment]
well approve it and we can see

**Pull request merged**
