### PR TITLE
Remove deprecated packages

### PR DESCRIPTION
**Pull request by gmarcos87**
I noticed that several packages from our repository are already deprecated and maintenance free. I will create a new place where you can rest in peace and remove the complexity and size of lime-packages.
The ones I found are:
- altermap-agent
- dnsmasq-distributed-hosts
- dnsmasq-lease-share
- vale
- cotonete
- smonit
- fft-eval

The ones I have doubts about are:
- lime-ap-watchping
- lime-hwd-usbradio
- lime-map-agent
- lime-webui
- luci-app-batman-adv
- luci-app-lime-location
- luci-app-openairview
- luci-lib-jquery-flot

I'm not saying delete the code from these packages but move them to a new legacy repository, respecting their history in git.

### CODE REVIEW

**Comment by ilario** [comment]
I can't find `dnsmasqdistributed-leases`, do you mean `dnsmasq-lease-share`?
This and also `dnsmasq-distributed-hosts` were used for LibreMesh 17.06 release so we could just leave them in the 17.06 branch and remove from master.
I doubt that any community wants to still use them (e.g. for creating a retrocompatible image) but we should ask on the lime-users list.

`lime-hwd-usbradio` sounds useful but I have no idea if it is being used by anyone. @G10h4ck ?

Maybe some more to consider: fft-eval (see #479), lime-basic-uing, smonit (we still need the deaf interface stuff, or not?).

**Comment by gmarcos87** [comment]
@ilario thank you for taking the typographical error, I change it.
Cotonete is for monitoring radios and solving the problem of deafness. When it is functional (@nicop can explain what work is still missing) smonit will not be necessary.
On metapackages I don't know what posture we adopt, like lime-baisc, lime-basic-uing, etc.

**Comment by spiccinini** [comment]
The only place that I see smonit is being used for ping_watchdog at this networks:
```
./mobilquattrosud.com/L2nodes/etc/smonit/ping_watchdog
./mobilquattrosud.com/L23nodes/etc/smonit/ping_watchdog
./trans.hackmeeting.org/L2nodes/etc/smonit/ping_watchdog
```
As we have the `watchping` package for this use case I propose to remove `smonit`

**Comment by nicopace** [comment]
> Cotonete is for monitoring radios and solving the problem of deafness. When it is functional (@nicop can explain what work is still missing) smonit will not be necessary.

I actually added the readme of it (Thanks @gmarcos87!):
https://github.com/libremesh/lime-packages/pull/573/commits/55e1dd104b71eaa64a00ed5316ad40f6fdb3c2c5

**Comment by nicopace** [comment]
@gmarcos87 i separated the code of cotonete in a repository on my user while it is in a beta state... wil lask to be reintegrated in lime once it is well tested.
https://github.com/nicopace/cotonete
Thanks!

**Comment by ilario** [comment]
From `libremesh.sdk.config` consider removing also:

```
CONFIG_PACKAGE_ALFRED_BATHOSTS=y
CONFIG_PACKAGE_vale=m
```

**Comment by spiccinini** [comment]
I think it is good to merge it as it is and leave further removals for other PRs

**Pull request merged**
