### PR TITLE
Sends link to built images to the PR

### PR DESCRIPTION
**Pull request by nicopace**
When a new build has succeded, it sends a comment to the Pull Request with the link for images to download.

### CODE REVIEW

**Comment by ilario** [comment]
Beware to use a token in the encrypted script which is not yours, I would create a new github user just for doing this, otherwise whoever has write access to .travis.yml could modify it for obtaining your token.

**Comment by nicopace** [comment]
Done!

**Comment by ilario** [comment]
Hey, shouldn't the link appear here?

**Comment by nicopace** [comment]
Added the change on https://github.com/libremesh/lime-packages/pull/205 in this pull request.
It is working ok! (I can't review my own PR, but please check!)

**Pull request merged**
