### PR TITLE
Copy documentation from lime-web to the firmware

### PR DESCRIPTION
**Pull request by ilario**
`lime-docs` downloads all the text files originating pages in http://libremesh.org/docs and puts it in `/docs` directory in firmware root;

`lime-docs-minimal` is thought to replace `/etc/config/lime-example`, following 3e3c0f8, #125 and #139. So it copies just the config.txt file from the aforementioned direction and puts it in the `/docs` directory in the firmware root.

I just checked that the image compiles ok, I can do test on a real router next week.

### CODE REVIEW

**Comment by G10h4ck** [comment]
The point made by Pau seems good to me, if the documentation is accessible also via HTTP is very good!

**Comment by ilario** [comment]
I applied the suggestions, please review.
Still have to test on real device.
I have a doubt: is it acceptable to introduce the subversion dependency for the host compiling the image? Or is it already a dependency of other LEDE stuff?

**Comment by G10h4ck** [comment]
subversion it's already a build dependency of LEDE/OpenWrt

**Comment by p4u** [comment]
Looks good to me.

Thanks!

**Pull request merged**
