### PR TITLE
Remove all conditional dependencies

### LINKED ISSUE #331: cascade of metapackages kills modularity
I'm trying to use lime with something else than the usual combination of bmx6+batman-adv.
However, this is currently nearly impossible because of a cascade of meta-packages which pull-in a lot of packages via their dependencies. I tried crafting a flavor with bmx7-only and failed because the current approach of meta-packages and flavors was left behind in the past when we were still always building everything from source. When using the ImageBuilder, things like
```
DEPENDS:=+PACKAGE_lime-proto-bmx6:luci-app-bmx6
```
won't work because `CONFIG_PACKAGE_lime-proto-bmx6=m` no matter if the user actually intended to use bmx6 at all.

Hence I suggest to entirely drop all **optional** things from the lime-basic, lime-full, lime-mini, lime-webui, ... packages. Those packages can then be pulled in via the dependencies of a community-profile-package of a community which makes use of them. In that way, modularity can be restored and selecting lime-basic or lime-webui won't automatically pull-in potentially unwanted packages.
I'm not only talking about routing protocols and autogw stuff, but also things like lime-hwd-openwrt-wan which I went through difficult loops only in order to finally get rid of it.

What do you think?
@aparcar @p4u @nicoechaniz @altergui @G10h4ck 

If you agree, I'll start working on a PR to remove all protocol-specific or somehow optional dependencies from the meta-packages.

### PR DESCRIPTION
**Pull request by ilario**
As reported by @dangowrt in #331, the conditional dependencies work only when compiling using the buildroot method (which is currently the recommended one, see https://libremesh.org/development.html) but not with methods employing the imagebuilder, like the [Chef](https://github.com/libremesh/chef) or the [metabuilder](https://github.com/aparcar/openwrt-metabuilder) (which are much more convenient and will have to be supported by the next release). 

Fixes #331

### CODE REVIEW

**Comment by G10h4ck** [comment]
I do not agree with this changes, chef and image builder should eventually solve their limitation instead.

Also something like chef could be programmed on top of the buildroot instead, which have lot mroe advantages and much less bugs that imagebuilder and similar...

**Comment by ilario** [comment]
> Also something like chef could be programmed on top of the buildroot instead

History is cyclic, they say. In august I commented https://github.com/libremesh/lime-packages/issues/558#issue-479568278

> compilation method has changed over the time (buildroot, lime-build, lime-sdk, buildroot)

and your comment means that we'll have the lime-build again!!!!!

**Comment by ilario** [comment]
In this PR I removed also batctl from lime-debug:
in OpenWrt 18.06 could be annoying but if we add a hard dependency on batctl, also kmod-batman-adv will be selected by lime-debug (as [kmod-batman-adv is a dependency of batctl in 18.06](https://openwrt.org/packages/pkgdata_owrt18_6/batctl))
the opposite happens in OpenWrt 19.07, so there's no need for lime-debug to depend on batctl as it [is a dependency of kmod-batman-adv](https://openwrt.org/packages/pkgdata/kmod-batman-adv).

**Comment by ilario** [comment]
I removed the commit about lime-proto-bmx6 which is better addressed in #716.

**Comment by ilario** [comment]
The following conditional dependencies are addressed in this PR.

- [ ] lime-proto-wan:	+!PACKAGE_firewall:iptables
- [ ] lime-proto-bmx6:	+!PACKAGE_firewall:iptables
- [x] lime-webui:	+PACKAGE_lime-proto-bmx6:luci-app-bmx6
- [x] lime-webui:	+PACKAGE_lime-proto-batadv:luci-app-batman-adv
- [x] lime-debug:	+PACKAGE_lime-proto-batadv:batctl
- [ ] shared-state-dnsmasq_leases:	@(!PACKAGE_dnsmasq-lease-share) (what is this syntax??)  this package does not even exist anymore!!!
- [x] lime-map-agent:	+PACKAGE_lime-proto-bmx6:luci-lib-libremap-bmx6

**Review by spiccinini — APPROVED** [review]

**Review by aparcar — APPROVED** [review]

**Pull request merged**
