### PR TITLE
Implementing Contiuous Integration

### PR DESCRIPTION
**Pull request by nicopace**
Based on https://github.com/probonopd/announce/blob/master/.travis.yml

### CODE REVIEW

**Comment by nicopace** [comment]
Blocked because of this:
* https://github.com/libremesh/lime-sdk/issues/13
* https://github.com/libremesh/lime-sdk/issues/12

**Comment by ilario** [comment]
libremesh/lime-sdk#13
has been solved by libremesh/lime-sdk#15

libremesh/lime-sdk#12
has a workaround forcing it to exit code 0 (via `|| true`) in .travis.yml file but was also forced to exit code 0 due to libremesh/lime-sdk#15

So what fails now is the cooking time that using Travis for free is limited to 50 minutes **for each thread** so maybe it's enough to split the compilation process in more than one command.
For example we can try adding `./cooker -b ar71xx/generic` before the actual cooking command?
Otherwise how could we split the cooking command in smaller tasks?

**Comment by ilario** [comment]
Travis fails when cooker fails, Travis works when cooker works. The running time is below 30 min (limited to 50 min from travis-ci.org). @nicopace what's missing? Should we merge all the commits in a few or one commit?

**Comment by ilario** [comment]
Example of a failing job: https://travis-ci.org/libremesh/lime-packages/jobs/259410507
Example of a working job: https://travis-ci.org/libremesh/lime-packages/jobs/259368260

**Pull request merged**
