### PR TITLE
translations 25 may to 14 june 2018

### PR DESCRIPTION
**Pull request by patogit**
translations from translatewiki.net

### CODE REVIEW

**Comment by aparcar** [comment]
Sorry for the confusion, but the develop branch is outdated and replaced by `master`. Please recreate the PR

**Comment by patogit** [comment]
Sooo...... that means we should change the translatewiki.net settings to pull from the master branch. Is this a long-term change, to doing development on the master branch, or something that will change again in a few weeks?

**Comment by patogit** [comment]
> Please recreate the PR

https://github.com/libremesh/lime-packages/pull/387

**Comment by aparcar** [comment]
Merged in master

**Pull request closed without merging**
