### PR TITLE
Fixing some dependencies

### PR DESCRIPTION
**Pull request by ilario**
As indicated in #940, I just realized that some dependencies are missing.
Here go some fixes, more will be added to this PR, please do not merge yet.

### CODE REVIEW

**Comment by ilario** [comment]
Many of these dependencies will have to be changed when we fix #771, but #771 is had its second birthday a few weeks ago, so it does not look like we're going to fix it soon (hope is still there).

**Comment by ilario** [comment]
My personal dependencies crusade is over, I am not sure I fixed everything (e.g. luci.tools stuff I didn't check where it is).
Just checked with the buildroot of OpenWrt 22.03 and no additional warning (the ones from libremap are still there, see https://github.com/libremesh/lime-packages/issues/929) appears, so it should be ok to merge.
I didn't check with OpenWrt 19.07 but none of the packages mentioned as dependencies should have been renamed since 2019.

**Comment by ilario** [comment]
One doubt: the `luci-lib-json` dependency has not been updated to `luci-lib-jsonc` for `luci-mod-status` and `luci-app-openairview`. I don't know if these two packages would work also with jsonC.

**Comment by ilario** [comment]
> Just checked with the buildroot of OpenWrt 22.03 and no additional warning (the ones from libremap are still there, see #929) appears, so it should be ok to merge. I didn't check with OpenWrt 19.07 but none of the packages mentioned as dependencies should have been renamed since 2019.

Correction: there IS a new warning.

```
tmp/.config-package.in:101823:error: recursive dependency detected!
tmp/.config-package.in:101823:	symbol PACKAGE_pirania is selected by PACKAGE_shared-state-pirania
tmp/.config-package.in:60861:	symbol PACKAGE_shared-state-pirania is selected by PACKAGE_pirania
For a resolution refer to Documentation/kbuild/kconfig-language.rst
subsection "Kconfig recursive dependency limitations"
```

I confirmed with OpenWrt 19.07 and this is the only new warning that appears with both 22.03 and 19.07.

Reported as a separate issue on #942

**Review by G10h4ck — APPROVED** [review]

**Pull request merged**
