### PR TITLE
Use SPDX License Identifier to shrink size

### PR DESCRIPTION
**Pull request by G10h4ck**

### CODE REVIEW

**Comment by ilario** [comment]
Do you plan to apply the same change to all the files (approx 34, see https://github.com/libremesh/lime-packages/search?q=MERCHANTABILITY ) or is this ready for merging?

**Comment by G10h4ck** [comment]
in the Lua files where the licence is commented with `--!` it should be stripped automatically on build, but if you would like to do that extensively i am ok with that

**Comment by ilario** [comment]
Right, most of the files have the -- thing, that's good.
The ones that does not have it are:

- [ ] packages/safe-upgrade/files/usr/sbin/safe-upgrade
- [ ] packages/shared-state-persist/files/usr/bin/shared-state-persist
- [ ] packages/lime-webui/luasrc/model/essentials.lua (abandoned)
- [ ] packages/lime-webui/luasrc/controller/lime.lua (abandoned)
- [ ] packages/shared-state/files/www/cgi-bin/shared-state
- [ ] packages/shared-state/files/www/cgi-bin/shared-state-multiwriter
- [x] packages/shared-state/files/usr/bin/shared-state-get_candidates_neigh
- [ ] packages/bmx7-mdns/files/luci/bmx7-mdns.lua (abandoned???)
- [ ] packages/luci-mod-status/files/usr/lib/lua/luci/controller/status/bmx6.lua (abandoned)

and these ones have a # instead:

- [ ] packages/bmx7-mdns/files/etc/init.d/bmx7-mdns  (abandoned???)
- [ ] packages/safe-reboot/files/usr/sbin/safe-reboot

**Comment by ilario** [comment]
@G10h4ck are you planning to include also the aforementioned files and their licenses in this pull request or should I merge only the one that is already fixed?

**Comment by G10h4ck** [comment]
Let merge this, and leave the rest for future PRs

**Review by nicoechaniz — APPROVED** [review]
ok

**Pull request merged**
