### PR TITLE
New packages: auto-usb-wwan and soporteremoto

### PR DESCRIPTION
**Pull request by altergui**
quick development for Cheran network

### CODE REVIEW

**Comment by altergui** [comment]
installing `soporteremoto` package will make the node install zerotier and join network `35c192ce9b5fa4cb` which will allow AlterMundi members to remotely access the node via SSH

**Comment by altergui** [comment]
installing `soporteremoto` package will make the node install zerotier and join network `35c192ce9b5fa4cb` which will allow AlterMundi members to remotely access the node via SSH

**Comment by altergui** [comment]
a minor note: currently, auto-usb-wwan will not properly configure a USB device that is connected on *first boot* (after flashing), because the hotplug.d runs before lime-config.
After reboot (and every boot afterwards), hotplug.d script will run again and properly set up the USB WWAN (without lime-config resetting wireless config)

**Comment by gmarcos87** [comment]
If you do lime-config and wifi or lime-apply in the node that is connected the usb dongle you can be without network access? Will lime-config recognize it as a 2ghz interface and reconfigure it atuomatically according to the modes set in /etc/config/lime?

**Pull request merged**
