### PR TITLE
Small cleaning

### PR DESCRIPTION
**Pull request by G10h4ck**
Change package maintainer, correct license, plus comment on the code

### CODE REVIEW

**Comment by ilario** [comment]
Can the title "provides data-type for user marked reliable network nodes" be more clear?

Can you add the description? Before merging?

Is German Ferrero part of Altermundi? I mean, why replacing his name instead of adding a new line?

**Comment by G10h4ck** [comment]
> Can the title "provides data-type for user marked reliable network nodes" be more clear?

Nope, it is exactly what that package does.


> Is German Ferrero part of Altermundi? I mean, why replacing his name instead of adding a new line?

He was, and that contribution was as part of it's Altermundi participation, now Altermundi is keeping on the maintenance of this package.

**Comment by ilario** [comment]
Ok, can you add the description?

**Comment by G10h4ck** [comment]
> Ok, can you add the description?

done

**Comment by ilario** [comment]
> > Ok, can you add the description?
> 
> done

Did you push?
Right now I can still see only a TODO as the description.

**Comment by ilario** [comment]
Thanks. With the new phrasing, also the title is muuuch more clear!

**Review by ilario — APPROVED** [review]

**Pull request merged**
