### PR TITLE
Add Chef to README.md and improvements

### PR DESCRIPTION
**Pull request by ilario**

### CODE REVIEW

**Comment by ilario** [comment]
Why was this closed? If it's just because it's outdated I can update it. Or there was something wrong with the added concepts?

**Comment by p4u** [comment]
Closing was not correct, sorry. It is fine but it needs some modifications.

1. Solve the merge conflicts
2. I would change the LiMe version to "Develop" instead of "Biggest Bang"

**Comment by ilario** [comment]
Updated. Is it ok now?

**Comment by ilario** [comment]
Ping

**Comment by p4u** [comment]
Thanks.

**Pull request merged**
