### PR TITLE
tinc: remove package

### PR DESCRIPTION
**Pull request by aparcar**
The package should be offered upstream to support multiple
architectures, as this is not part of the LiMe build system.

It was initially introduced for LibreNet6, which required tinc 1.1pre
while packages.git only offers tinc 1.0.36. Instead of having a arch
dependent package in a *archless* feed, remove it now and hope it's
available in packages.git soon.

Signed-off-by: Paul Spooren <mail@aparcar.org>

### CODE REVIEW

**Comment by ilario** [comment]
Do you think this will happen? The release cycle of Tinc seems very slow.
@zioproto (ciao!!) do you have any insight?

Anyway I agree that it makes little sense to have Tinc in our repository.

@spiccinini @nicopace @gmarcos87 @germanferrero @altergui @p4u @G10h4ck @dangowrt @nordurljosahvida @FreifunkUFO do you know if anyone is using the lime-librenet6 (related #579) or the tinc package from our repositories?

**Review by spiccinini — APPROVED** [review]
I am ok with this

**Comment by aparcar** [comment]
@spiccinini good point, let's remove it.

**Comment by zioproto** [comment]
Related issue: https://github.com/openwrt/packages/issues/13555

**Comment by aparcar** [comment]
@ilario please approve

**Review by ilario — APPROVED** [review]
Good to remove from lime-packages repository. Let's hope that a `tinc-pre` package appears in the OpenWrt packages soon.

**Pull request merged**
