### PR TITLE
Add Chef and Matrix chatroom to README.md

### LINKED ISSUE #256: Update readme with Chef and contact channels
* Add a tiny section mentioning the existence of chef and a link to the repository and official website.
* Either add Matrix channel in contacts or empty that section and leave just a link to http://libremesh.org/communication.html

### PR DESCRIPTION
**Pull request by radikalbjr**
Fixes #256

### CODE REVIEW

**Comment by G10h4ck** [comment]
Libremesh team doesn't support matrix by any means so please remove it from the readme, I have removed it from the website in the past

**Comment by ilario** [comment]
The discussion on the Matrix chat is [here](https://lists.libremesh.org/pipermail/lime-users/2017-October/thread.html#944) and [here](https://lists.libremesh.org/pipermail/lime-users/2018-February/thread.html#1079); there's an issue open since 2017 asking for this PR: #256; IRC is not the official channel neither, see #247 (maybe the official chat is the one on Mattermost or the one on Telegram?); there's no element in this PR that saying that [Libremesh team](https://libremesh.org/about.html) supports Matrix.
Maybe @radikalbjr could add a line making this explicit?
Something like:

```
- Chatroom on [Matrix net][12].
+ Chatroom accessible via [Matrix net][12] (not supported by Libremesh team) or via [IRC][13] (user registration required, not supported by Libremesh team).
```

**Comment by G10h4ck** [comment]
> > I think the chatroom on Altermundi mattermost instance is the only supported chat ATM
> 
> Isn't that a somewhat internal thing?

There is both an internal channel, and a public one

**Comment by radikalbjr** [comment]
For the public chatroom both registration and invitation is required. There is no way to ask for an invitation in the mattermost interface. This should be changed in order to have a public, official and accesible chat IMHO

**Comment by nicopace** [comment]
@nicoechaniz can you jump on this?

**Comment by aparcar** [comment]
I'm in favor of removing the matrix channel here and only advise the online ImageBuilder. Problem of instant chat is people are sad nobody responds to their complex problems. Let them write a mail so they won't have to idle days in a IRC channel. 

I'll close this PR for now and use the IB related parts, in case you disagree, please reopen.

**Comment by aparcar** [comment]
https://github.com/libremesh/lime-packages/pull/437

**Comment by ilario** [comment]
Please have a look at libremesh/lime-web#73

**Pull request closed without merging**
