### PR TITLE
replace dnsmasq-dhcpv6 with odhcpd-ipv6only

### PR DESCRIPTION
**Pull request by aparcar**
eventually solving a whole stack of issues

### CODE REVIEW

**Comment by G10h4ck** [comment]
have you tested if everything keeps working as expected?

**Comment by nicopace** [comment]
As this are critical features, we need to test on devices and on networks.
Would say @G10h4ck @nicoechaniz and me at least to test on devices before merge.
Still a WIP although, so just let us know @aparcar

**Comment by nicopace** [comment]
A lot of changes got into this @aparcar ... 
hope you can clean up.

**Comment by aparcar** [comment]
I just messed up the PR with some rebasing. Now it's clean again.
On the snapshot server I created some images running with the modified version, works here for me
https://snapshots.libremesh.org/staging/aparcar/targets/

**Comment by aparcar** [comment]
Generally I'd suggest to remove the distributed hosts thing and replace it with the to be created `mesh-dns`.

**Comment by gmarcos87** [comment]
Now that alfred was replaced by shared-state we should change that too. Also pirania depends on dnsmasq to redirect traffic.
I would like to know a little more about the advantages of this migration, currently the behavior of dnsmasq is not being conflictive.

**Pull request closed without merging**
