### PR TITLE
Testing Batman-adv on ethernet, replaces #703

### PR DESCRIPTION
**Pull request by ilario**
#703 got messy (sorry for that) and this has the same content, including the rework by @G10h4ck.
See discussion on #703 and #56

### CODE REVIEW

**Comment by G10h4ck** [comment]
opened another one with conflict fixed https://github.com/libremesh/lime-packages/pull/726

**Comment by markbirss** [comment]
Oh this good news, adding back support for Batman-adv over ethernet 

I have been busy with this also just recently without LibreMesh with devices without radio's
e.g

Cisco Meraki MX60
Cisco ON100
Samsung CY-SWR1100 (the onboard radio's never worked with OpenWRT)

but will test also when I get some time

Im also waiting for some 10Gbit Fiber Networks cards that are supported under OpenWRT for X86 builds

**Comment by markbirss** [comment]
Ok, i tested snapshot with LibreMesh changed routing_also to BATMAN_V (to see reported Ethernet throughput) on my 

Cisco ON100 - does not work correctly, only has eth0 and eth1 ethernet

Cisco MX60  seems ok ( yes - 1000 )
Samsung CY-SWR1100 seems ok  ( no - 1.0 ) 

also

I tried separate vlan on each port to have as many as 3 bat interface
to have a switch for batman-adv over Ethernet

batman bonding is not working as speed reduces and then reaches 0 (with batctl tp)

**Comment by markbirss** [comment]
Hi All

How do I confirm if routing is actually over batman-adv ?

**Comment by ilario** [comment]
Gosh... I usually check the output of `ip route` and `batctl o`

**Comment by markbirss** [comment]
@ilario 

im not sure my current test setup configuration or build is actually correct?

Could you further detail a test configuration for ethernet only ?

I have disabled wifi and removed wifi related interfaces totally

i have firmware snapshot openwrt with libremesh snapshot feeds

I have hardware

1 x TP-Link TL-WR1043NDv1 
1 x Cisco Meraki MX60
1 x Samsung CY-SWR1100

I have connected them together either via LAN ports or from LAN to WAN ports and have internet access on the Cisco Meraki MX60 via WAN port

if I for example rmmod batman-adv i can still ping to internet?

**Comment by ilario** [comment]
I think we should move this conversation away from this pull request (in favour of the lime-users mailing list or of the chat room, see https://libremesh.org/communication.html ) and only report here the conclusion.

Anyway I never tested the ethernet only option, it's interesting.
In order to disable the mesh via wifi, simply add a couple of lines in `/etc/config/lime-node`:

```
config lime system

config lime network

config lime wifi
	list modes 'ap'
	list modes 'apname'
```

this will override the default list of wifi modes (which includes `ieee80211s` mesh).

Never never never connect two LibreMesh nodes LAN to WAN, always LAN to LAN.

Do not yet use LibreMesh on top of OpenWrt snapshot (we never tested with the latest OpenWrt changes), on top of OpenWrt 19.07 should work (I would go this way), on top of OpenWrt 18.06 surely works.

If you remove batman-adv module I suppose that in some cases things will work (e.g. networks with < 2 nodes) but normally it should not work (see #666) as nobody implemented the possibility to use LibreMesh without Batman-adv, I believe.

**Comment by markbirss** [comment]
@ilario 
understood

**Pull request closed without merging**
