### PR TITLE
lime-proto-batadv VLAN ID start from 20 rather than from 16 and keep old default VLAN ID

### PR DESCRIPTION
**Pull request by ilario**
See the discussion on #676
This PR is an alternative to #676 
Retrocompatibility with the previous release is not going to happen anyway, so this keeps the retrocompatibility just for the users using development code.
At the price of a bit more weird way to calculate the VLAN ID.

### CODE REVIEW

**Comment by G10h4ck** [comment]
I'd start from 30, we are already really really near 20...
Have you tested the new code?

**Comment by spiccinini** [comment]
> I'd start from 30, we are already really really near 20...
> Have you tested the new code?

VLAN ids from 0 to 19 are not available? Also above 256 + 20 can be used

**Comment by G10h4ck** [comment]
AFAIR some hardware switch behave badly with big VLAN ids, so the 256 limitation probably comes from there

**Comment by ilario** [comment]
> I'd start from 30, 

If we want to start from 30 we could as well use the easy approach from #676 as the "retrocompatibility" would be lost anyway (remember that currently the default BATMAN-adv VLAN ID is 29).

> we are already really really near 20...

What's the problem? We can start using the VLAN ID between 1 and 12 (using 802.1ad, while I suppose that if we wanted to use 802.1q we should stay away from small numbers, correct?) or between 276 and 4095.

> Have you tested the new code?

I didn't but now I did :)
Using the default ESSID "LibreMesh.org" still results in the ID 29 which is what differentiates this PR from #676.
Using AP_SSID "y" the %N1 is zero and the ID is 272.
Using AP_SSID "ooo1" the %N1 is 3 and the ID is 275.
Using AP_SSID "xxxx1" the %N1 is 4 and the ID is 20.
Using AP_SSID "p1" the %N1 is 255 and the ID is 271.
So, it works as expected.

PS: I just noticed a little stupid thing: the MD5 we use for calculatin %N1 in lime-system/utils.lua takes also a newline after the AP_SSID, so we're using the MD5 of "LibreMesh.org\n" instead of that of "LibreMesh.org". But this has no impact at all and I would not change this.

PPS: please read and comment if possible on my comment about BATMAN-adv's own VLAN mechanism here: https://github.com/libremesh/lime-packages/issues/581#issuecomment-573362953

**Comment by G10h4ck** [comment]
> > I'd start from 30,
> 
> If we want to start from 30 we could as well use the easy approach from #676 as the "retrocompatibility" would be lost anyway (remember that currently the default BATMAN-adv VLAN ID is 29).

ok so lets start from 29

**Comment by ilario** [comment]
> ok so lets start from 29

Done

**Comment by ilario** [comment]
@spiccinini I added that line :) thanks

**Comment by spiccinini** [comment]
Thanks @ilario sorry for the delay

**Pull request merged**
