### PR TITLE
Refactor libremesh.mk and makefiles

### LINKED ISSUE #825: Errors in eupgrade Makefile
Reported by Jürgen on https://lists.libremesh.org/pipermail/lime-users/2020-December/001864.html
```
ERROR: please fix package/feeds/libremesh/eupgrade/Makefile - see logs/package/feeds/libremesh/eupgrade/dump.txt for details
Collecting package info: done
tmp/.config-package.in:72848:error: recursive dependency detected!
For a resolution refer to Documentation/kbuild/kconfig-language.txt
subsection "Kconfig recursive dependency limitations"
tmp/.config-package.in:72848: symbol PACKAGE_profile-freifunk-80211s-sae-bmx7-batadv depends on PACKAGE_kmod-cfg80211
For a resolution refer to Documentation/kbuild/kconfig-language.txt
subsection "Kconfig recursive dependency limitations"
tmp/.config-package.in:18758: symbol PACKAGE_kmod-cfg80211 is selected by PACKAGE_kmod-batman-adv
For a resolution refer to Documentation/kbuild/kconfig-language.txt
subsection "Kconfig recursive dependency limitations"
tmp/.config-package.in:13280: symbol PACKAGE_kmod-batman-adv is selected by PACKAGE_lime-proto-batadv
For a resolution refer to Documentation/kbuild/kconfig-language.txt
subsection "Kconfig recursive dependency limitations"
tmp/.config-package.in:73299: symbol PACKAGE_lime-proto-batadv is selected by PACKAGE_profile-freifunk-80211s-sae-bmx7-batadv
tmp/.config-package.in:141221:error: recursive dependency detected!
For a resolution refer to Documentation/kbuild/kconfig-language.txt
subsection "Kconfig recursive dependency limitations"
tmp/.config-package.in:141221: symbol PACKAGE_wpad-mesh-wolfssl is selected by PACKAGE_wpad-mesh-wolfssl
configuration written to .config

  I didn't touch wolfssl at all.  

And dump.txt:


Package: eupgrade
Version: x
Depends: +libc +GCC_LIBSSP:libssp +USE_GLIBC:librt +USE_GLIBC:libpthread
Conflicts:
Menu-Depends:
Provides:
Section: lime
Category: LibreMesh
Repository: base
Title:
Maintainer:
Source:
Type: ipkg
Description:
https://github.com/libremesh/lime-packages/

@@

../../libremesh.mk:63: *** Package/eupgrade is missing the TITLE field.  Schluss.

```

### PR DESCRIPTION
**Pull request by spiccinini**
The idea is to be able to use libremesh.mk like a module so that it can be more easily customized.

I still have to test a full build with this, but want to share the idea to get feedback.

Fixes #825

### CODE REVIEW

**Comment by G10h4ck** [comment]
This looks much better to me!

**Comment by spiccinini** [comment]
Ok so I've built an image with this changes, so far so good.

**Comment by spiccinini** [comment]
Ping! @ilario what do you think?

**Comment by ilario** [comment]
Did not test, looks working to me

**Review by ilario — APPROVED** [review]

**Review by G10h4ck — APPROVED** [review]

**Pull request merged**
