### PR TITLE
shared-state: get_candidates_neigh reduce ping interval to 0.2s

### PR DESCRIPTION
**Pull request by spiccinini**
This will speed up the process, even if it will be cached if there are too many neighbour it takes a lot of time, at least 4s per neighbour. Now it will take x5 less time

### CODE REVIEW

**Comment by gmarcos87** [comment]
I ran the script on a pretty core node of quintanalibre (si-radio). The result varied in each run between 2, 5 and 6 nodes detected. Perhaps it is too short a time to achieve a consistent result.

**Comment by spiccinini** [comment]
> I ran the script on a pretty core node of quintanalibre (si-radio). The result varied in each run between 2, 5 and 6 nodes detected. Perhaps it is too short a time to achieve a consistent result.

Maybe we can increse the time but reduce from 2 pings to 1?

**Comment by gmarcos87** [comment]
I tried different combinations of values and I can never reproduce the same state. Maybe what we should do is remove the cache or reduce its duration, however shared-state-get_candidates_neigh now responds more quickly

**Comment by spiccinini** [comment]
> I tried different combinations of values and I can never reproduce the same state. Maybe what we should do is remove the cache or reduce its duration, however shared-state-get_candidates_neigh now responds more quickly

This may be because hidden node node problems. As we are pinging to broadcast responses may be colliding (and lost) if not all the receiver nodes hear at each other.

Through the wireless interfaces it may be better to not ping but to use the `iwinfo.nl80211.assoclist` filtering only stations with less than N seconds of inactive time, and then convert the mac address to the fe80 ipv6 address.   What do you think @gmarcos87 @G10h4ck @nicopace ?

**Comment by nicopace** [comment]
I like the strategy @spiccinini .
Also, having a clear strategy that is different for different types of links makes sense.
We need to by mindful though, that not always an antenna that is connected in mesh/adhoc mode is another libremesh, but can be a device that is bridging with a libremesh node through a cable... the ping is the most effective one (or a broadcast package like the mikrotik does).
Still, maybe we can assume there is someone, and then still ping to make sure it is there.

**Comment by spiccinini** [comment]
Just as a reminder, luci.ip has the ability to convert from MAC to link local ipv6 and back:

```
> luci.ip.new("fe80::6666:b3ff:fe47:e1b9")
> print(addr:tomac())
64:66:B3:47:E1:B9
```
```
> ip = luci.ip.new("64:66:B3:47:E1:B9")          
> print(ip:tolinklocal())
fe80:51::31:6666:b3ff:fe47:e1b9
```

**Comment by gmarcos87** [comment]
> Just as a reminder, luci.ip has the ability to convert from MAC to link local ipv6 and back:

source

Initially we used the associated list, but that leaves out the links via eth that are necessary to capture as well.

**Comment by spiccinini** [comment]
> Initially we used the associated list, but that leaves out the links via eth that are necessary to capture as well.

I propose to use ping for ETH and the assoclist for wireless, what do you think?

**Comment by gmarcos87** [comment]
@spiccinini its ok for me

**Comment by gmarcos87** [comment]
Okay, this is gonna be impossible.
I'd better pull now and resume this task in the near future. It was worth a try

**Comment by G10h4ck** [comment]
> > Initially we used the associated list, but that leaves out the links via eth that are necessary to capture as well.
> 
> I propose to use ping for ETH and the assoclist for wireless, what do you think?

I remember we considered this option when talking about shared-state in la quintana, but don't remember why we didn't implemented it in the end, probably it didn't covered some corner case, BTW as I can't remember I'd approve this and see what happens :p

**Comment by G10h4ck** [comment]
Rereading the discussion I remembered that one of the cases not covered by using assoclist on wifi interfaces, is when on ONLY on one side a dumb wifi device is used to connect and bridge to another LiMe device via ethernet, I am not sure we have any of those cases in reality.

**Comment by spiccinini** [comment]
Here is an attempt at implementing what we have been discusing in this thread.

**Review by G10h4ck — APPROVED** [review]
A ver como se porta en la quintana con esta cambio ;)

**Pull request merged**
