### PR TITLE
use channels 157 and 48 for 5.8GHz

### PR DESCRIPTION
**Pull request by spiccinini**
channel 157 is FCC approved for outdoor use

Signed-off-by: Santiago Piccinini <spiccinini@altermundi.net>

TODO: test with devices with only one radio

### CODE REVIEW

**Comment by aparcar** [comment]
I guess it's better to have 48 as first entry to stay compatible with existing setups, not?

Regarding dual radios, I once wrote lime-smart-wifi, however would be better not be implemented in the core, not?

**Comment by G10h4ck** [comment]
> I guess it's better to have 48 as first entry to stay compatible with existing setups, not?
> 
> Regarding dual radios, I once wrote lime-smart-wifi, however would be better not be implemented in the core, not?

because the first 5Ghz interfaces is usually named wlan1 it will get channel 48 by default

**Comment by spiccinini** [comment]
> > I guess it's better to have 48 as first entry to stay compatible with existing setups, not?
> > Regarding dual radios, I once wrote lime-smart-wifi, however would be better not be implemented in the core, not?
> 
> because the first 5Ghz interfaces is usually named wlan1 it will get channel 48 by default

Thanks Gio for commenting on this. In my tests the first 5GHz interface get's the 48 channel.

**Comment by aparcar** [comment]
so when using a dual 5GHz only device, it's wlan0 157 and wlan1 48?

**Comment by G10h4ck** [comment]
> so when using a dual 5GHz only device, it's wlan0 157 and wlan1 48?

yes

**Pull request merged**
