### PR TITLE
lime-proto-bmx7: enable SMS plugin

### PR DESCRIPTION
**Pull request by aparcar**
The [SMS plugin](https://github.com/bmx-routing/bmx7#sms-plugin) can be very useful for various projects

See https://github.com/libremesh/lime-packages/issues/104

### CODE REVIEW

**Comment by aparcar** [comment]
@p4u ping

**Comment by G10h4ck** [comment]
Isn't the dependency on the plugin needed too? Or it just ignore it if it is not installed?

**Comment by aparcar** [comment]
@G10h4ck no it's just not enabled by default

**Comment by p4u** [comment]
bmx7-sms plugin is already a dependency for lime-proto-bmx7

**Pull request merged**
