### PR TITLE
fix #170 

### LINKED ISSUE #170: firmware upgrade via webui simple mode: no keep-no-settings
trying firmware upgrade via "simple mode" gives me no chance to say "keep no settings".
its mentioned on the webui, but there is no checkbox!

unchecking the "keep settings" checkbox is very important, because libremesh is an autoconfig mesh firmware.. (so keeping settings is not needed for most of the devices. To uncheck that option is mandatory for testing)

no-keep-no-settings

### PR DESCRIPTION
**Pull request by aparcar**
remove misleading "keep settings" in sysupdgrade view

### CODE REVIEW

**Comment by ilario** [comment]
+1
It would be useful to specify that the sysupgrade (and not the factory) image should be used here.

**Comment by aparcar** [comment]
@ilario does that make a difference for the lime-sysupgrade?

**Comment by ilario** [comment]
Hm... I suppose so... I always thought that there was a real reason for the existence of "-sysupgrade.bin" images but I never verified this!

**Comment by nicopace** [comment]
I flashed non-sysupgrade images with openwrt and they worked just fine... we discussed this with Gui in the past... you should try to clarify this once and for all.

**Comment by ilario** [comment]
So the existence of "-sysupgrade.bin" images when "-factory.bin" is also present is completely useless waste of disk space, compilation time and confusing for users...... WTF
Ok, @aparcar sorry for asking that change, it was not needed (but helps to reduce confusion for end user).

**Comment by nicopace** [comment]
@ilario please test!

**Comment by aparcar** [comment]
@ilario factory is still needed for initial flash from stock. No waste of space unless you want to first flash pure LEDE (factory image) and LiMe sysupgrade afterwards. 

I'd stick to the current formulation and keep the factory images on the server as well.

**Comment by nicopace** [comment]
The question @aparcar is if sysupgrade is needed :)

**Comment by ilario** [comment]
Regarding the PR: for me is ok for merge.

**Comment by ilario** [comment]
This is just a change of text in a webpage, no reason for delaying, I merge.

**Pull request merged**
