### PR TITLE
various readme improvements

### PR DESCRIPTION
**Pull request by aparcar**
Let's clean things up a little bit and let people use use the ImageBuilder.

### CODE REVIEW

**Comment by G10h4ck** [comment]
For new WiFi 6 radios, we might end up needing a custom build for hostapd, is this possible with imagebuilder?

**Comment by aparcar** [comment]
uhm... why do we need custom builds with the imagebuiler? I'm running LibreMesh successfully on WiFi 6 (and 7) devices with images based on the ImageBuilder.

**Comment by ilario** [comment]
Don't you have any problem with dnsmasq-ipv6? https://github.com/libremesh/lime-packages/issues/1000#issuecomment-1497391930

I think that apart from that, we are already compatible with the image builder for the core packages (see #1000 for problems with non-core packages).

**Comment by pony1k** [comment]
@ilario Why should there be a problem with `dnsmasq-ipv6`? When I specify `PACKAGES=-dnsmasq [...]`, imagebuilder builds without dnsmasq.

**Comment by ilario** [comment]
> When I specify `PACKAGES=-dnsmasq [...]`, imagebuilder builds without dnsmasq.

Ooh, I didn't know that was possible, nice!

**Comment by ilario** [comment]
Confirmed, you need to add "-dnsmasq", otherwise you have file conflicts with "dnsmasq-dhcpv6".
So I would merge this and then:
1) add the "-dnsmasq"
2) add a minimum amount of recommended packages (maybe babeld alone works, but I feel is not tested enough for suggesting that in the readme). So adding "lime-proto-batadv lime-proto-anygw lime-hwd-openwrt-wan" (last one is for having the WAN port configured as WAN)

@aparcar should I merge and do that edits or can you add this to the pull request? Thanks for this amazing work!

**Comment by aparcar** [comment]
Kindly proceed.

**Review by ilario — APPROVED** [review]

**Pull request merged**
