### PR TITLE
Change lime-defaults to use Ipv6 private ULA addresses

### LINKED ISSUE #656: Use private instead of public ipv6 addresses
The proposal is to use RFC4193 ULA addresses  aka `fd00::/8`

Quoting from this comment https://github.com/libremesh/lime-packages/issues/236#issuecomment-359461126

> Our currenty way of having an publicly routed default IPv6 prefix
> (literally **everybody** uses 2a00:1508:0a42:2400::/64) as the default
> prefix for LiMe nodes is wrong in a couple of ways:
> - this prefix can impossibly be routed back to all nodes using it
> - using addresses within that prefix as a source address will hence
>   only work in a single-gateway scenario **having exactly this prefix
>   delegated from upstream**
> - RAs with that public prefix are sent out and hence clients pick
>   (unreachable form outside) addresses, and as the default gateway
>   is also within the 2000::/4 range it will make clients believe
>   that we got access to other public IPv6 destinations which isn't
>   true in most cases -- this will slow down surfing as browsers
>   sometimes try reaching IPv6 addresses and fail.

> I suggest to move the default main_ipv6_address into an
> network-name-hash-based ULA prefix, e.g. fd%N1:%N2%N3:%N4%N5::/48 or
> something like that to decrease the overall confusion...

### PR DESCRIPTION
**Pull request by spiccinini**
Fixes #656

### CODE REVIEW

**Comment by ilario** [comment]
Works!
Could you adapt the documentation in lime-example here
https://github.com/libremesh/lime-packages/blob/3c76578e5c51dd6ffdadb0e2d3b61f016f52deab/packages/lime-docs/files/lime-example#L8

and here?
https://github.com/libremesh/lime-packages/blob/3c76578e5c51dd6ffdadb0e2d3b61f016f52deab/packages/lime-docs/files/lime-example#L76

**Comment by ilario** [comment]
Is there a difference between using /64 or /48 here? I mean, we're fixing just the first 3 fields of the IPv6, so /48 would be an option, right?

**Comment by ilario** [comment]
Also fixes #236

**Comment by G10h4ck** [comment]
Shouldn't we change this in lime-default-factory too?

**Comment by ilario** [comment]
@G10h4ck lime-default-factory introduced in #434 has been annihilated in #635, in two days it would have been its birthday.

**Comment by G10h4ck** [comment]
> @G10h4ck lime-default-factory introduced in #434 has been annihilated in #635, in two days it would have been its birthday.

`sed 's/lime-default-factory/lime-default/g`

**Comment by ilario** [comment]
> > @G10h4ck lime-default-factory introduced in #434 has been annihilated in #635, in two days it would have been its birthday.
> 
> `sed 's/lime-default-factory/lime-default/g`

Ah, it is already edited also in lime-defaults, can you check if it is ok?

**Pull request merged**
